services:
  app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    environment:
      - MAIN_URL=${MAIN_URL}
      - PORT=${PORT}
    volumes:
      - ./:/app
